Handle asyncio.exceptions.IncompleteReadError too which is sometimes raised as below:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1327, in async_device_update
    await self.async_update()
  File "/config/custom_components/regoheatpump/entity.py", line 81, in async_update
    self._process_value(await self._heat_pump.read(self._register))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/regoheatpump/rego600/heatpump.py", line 58, in read
    return await self.__send(*register.read(), retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/regoheatpump/rego600/heatpump.py", line 75, in __send
    return await self.__synchronised_send(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        payload, decoder, transformation, retry
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/regoheatpump/rego600/heatpump.py", line 106, in __synchronised_send
    response = await self.__connection.read(decoder.length)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/regoheatpump/rego600/serial_connection.py", line 59, in read
    return await self.__reader.readexactly(length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/asyncio/streams.py", line 767, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 5 expected bytes